const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const {stripTypeScriptTypes}=require('node:module');
const source=stripTypeScriptTypes(fs.readFileSync(require.resolve('../supabase/functions/publish-slice/index.ts'),'utf8'));
const good={url:'https://example.com/play',title:'Play',description:'Try',preview_hash:'a'.repeat(64),request_id:'12345678-1234-1234-1234-123456789abc',confirmed:true};
function setup({authenticated=true,changed=false}={}){let handler;const calls=[];const context=vm.createContext({Request,Response,AbortSignal,TextDecoder,Uint8Array,fetch:async(url,options)=>{calls.push({url,options});if(url.endsWith('/auth/v1/user'))return Response.json(authenticated?{id:'creator'}:{error:'invalid'},{status:authenticated?200:401});if(url.includes('vercel.app'))return Response.json({status:'preview',source:{source_type:'url'},version:{content_hash:changed?'b'.repeat(64):good.preview_hash,html:'<button>Tap</button>'}});return Response.json('slice-id');},Deno:{env:{get:n=>n==='SUPABASE_URL'?'https://project.supabase.co':'server-only-test-key'},serve:fn=>handler=fn}});vm.runInContext(source,context);return {calls,handler};}
const request=(body=good,authorization='Bearer user-token')=>new Request('https://project.supabase.co/functions/v1/publish-slice',{method:'POST',headers:{Authorization:authorization,'Content-Type':'application/json'},body:JSON.stringify(body)});
test('cloud publication requires a verified session and creator confirmation',async()=>{let s=setup();assert.equal((await s.handler(request(good,''))).status,401);assert.equal(s.calls.length,0);s=setup({authenticated:false});assert.equal((await s.handler(request())).status,401);assert.equal(s.calls.length,1);s=setup();assert.equal((await s.handler(request({...good,confirmed:false}))).status,400);assert.equal(s.calls.length,1);});
test('source changed since preview cannot publish',async()=>{const s=setup({changed:true});assert.equal((await s.handler(request())).status,409);assert.equal(s.calls.length,2);});
test('verified artifact goes to transaction RPC; bearer never goes to source acquisition',async()=>{const s=setup();const result=await s.handler(request());assert.equal(result.status,200);assert.equal((await result.json()).id,'slice-id');assert.equal(s.calls[1].url,'https://slice-jade.vercel.app/api/import/url');assert.equal(s.calls[1].options.headers.Authorization,undefined);assert.equal(s.calls[2].url,'https://project.supabase.co/rest/v1/rpc/publish_verified_slice');const body=JSON.parse(s.calls[2].options.body);assert.equal(body.p_creator,'creator');assert.equal(body.p_request,good.request_id);assert.equal(body.p_version.content_hash,good.preview_hash);});
