const {test}=require('node:test');const assert=require('node:assert/strict');
const {Readable}=require('node:stream');const https=require('node:https');const {EventEmitter}=require('node:events');
const {publicIP,validateURL,acquireURL,requestPage,MAX_BYTES}=require('../server/import/acquire.cjs');
const {importSource,inspect}=require('../server/import/pipeline.cjs');
const html='<title>Tap lab</title><button onclick="this.textContent=123">Tap</button>';
const lookup=async()=>[{address:'93.184.216.34',family:4}];
test('valid public HTTPS HTML yields preview only, separate source and version',async()=>{const p=await importSource({source_type:'url',source_url:'https://example.com'},{lookup,request:async()=>({html,bytes:html.length})});assert.equal(p.status,'preview');assert.equal(p.source.resolved_url,'https://example.com/');assert.equal(p.version.version,1);assert(!p.slice);});
test('protocols, credentials, private/reserved hosts and IPv6',()=>{for(const value of ['file:///etc/passwd','ftp://example.com','http://example.com','https://localhost','https://127.1','https://10.1.2.3','https://172.16.0.1','https://192.168.0.1','https://169.254.169.254','https://[::1]','https://[::ffff:127.0.0.1]','https://metadata.google.internal','https://user:pass@example.com','https://example.com:8443'])assert.throws(()=>validateURL(value),value);for(const ip of ['0.0.0.0','100.64.0.1','192.0.0.1','224.0.0.1','fc00::1','fe80::1','2001:db8::1'])assert.equal(publicIP(ip),false,ip);});
test('DNS checks all addresses and rejects private redirect',async()=>{await assert.rejects(acquireURL('https://example.com',{lookup:async()=>[{address:'10.0.0.1',family:4}]}),/private/);let calls=0;await assert.rejects(acquireURL('https://example.com',{lookup,request:async()=>{calls++;return {redirect:'https://127.0.0.1'};}}),/Private/);assert.equal(calls,1);await assert.rejects(acquireURL('https://example.com',{lookup,request:async()=>({redirect:'/loop'})}),/redirect/);});
test('DNS timeout',async()=>{await assert.rejects(acquireURL('https://example.com',{lookup:()=>new Promise(()=>{}),timeoutMs:10}),/timed out/);});
test('dangerous capabilities and passive content fail compatibility',()=>{for(const code of ['<script src="/a.js"></script>','<iframe srcdoc="x"></iframe>','<script>navigator.serviceWorker.register("x")</script>','<script>window.open("x")</script>','<script>top.location="x"</script>','<script>fetch("/api")</script>','<style>@import "x"</style>','<img src="https://example.com/a">','<meta http-equiv="refresh" content="0;url=x">'])assert(inspect(html+code).issues.length,code);assert(!inspect('<h1>static</h1>').interactive);});
test('transport caps response, validates HTML, pins DNS and sends no credentials',async()=>{
 const original=https.get;
 async function run(headers,chunks){https.get=(url,options,callback)=>{assert.equal(options.headers.Cookie,undefined);assert.equal(options.headers.Authorization,undefined);options.lookup('example.com',{},(err,ip)=>assert.equal(ip,'93.184.216.34'));const req=new EventEmitter();process.nextTick(()=>{const res=Readable.from(chunks);res.statusCode=200;res.headers=headers;callback(res);});return req;};return requestPage(new URL('https://example.com'),{address:'93.184.216.34',family:4},new AbortController().signal);}
 try{await assert.rejects(run({'content-type':'application/json'},['{}']),/HTML/);await assert.rejects(run({'content-type':'text/html','content-length':String(MAX_BYTES+1)},[]),/300 KB/);await assert.rejects(run({'content-type':'text/html'},[Buffer.alloc(MAX_BYTES),Buffer.from('x')]),/300 KB/);assert.equal((await run({'content-type':'text/html'},[Buffer.from(html)])).html,html);}finally{https.get=original;}
});
test('network body timeout aborts transport',async()=>{const original=https.get;https.get=(url,options)=>{const req=new EventEmitter();options.signal.addEventListener('abort',()=>req.emit('error',Error('aborted')));return req;};try{await assert.rejects(acquireURL('https://example.com',{lookup,timeoutMs:10}),/timed out/);}finally{https.get=original;}});
test('redirect to DNS-private host is rejected before a second socket; final public URL recorded',async()=>{
 let count=0;await assert.rejects(acquireURL('https://example.com',{lookup:async host=>[{address:host==='example.com'?'93.184.216.34':'192.168.1.1',family:4}],request:async()=>{count++;return {redirect:'https://private.example.com'};}}),/private/);assert.equal(count,1);
 await assert.rejects(acquireURL('https://example.com',{lookup:async()=>[{address:'93.184.216.34',family:4},{address:'::1',family:6}]}),/private/);
 count=0;const p=await acquireURL('https://example.com',{lookup,request:async()=>count++?{html,bytes:html.length}:{redirect:'/final'}});assert.equal(p.source_url,'https://example.com/');assert.equal(p.resolved_url,'https://example.com/final');
});
test('GitHub adapter cannot acquire or execute a project',async()=>{await assert.rejects(importSource({source_type:'github'}),/Coming soon/);});
